---
# Create jellyfin user
- name: Ensure group "{{ jellyfin_user.name }}" exists
  ansible.builtin.group:
    name: "{{ jellyfin_user.name }}"
    state: present
    gid: "{{ jellyfin_user.gid }}"

- name: Create jellyfin user
  ansible.builtin.user:
    name: "{{ jellyfin_user.name }}"
    group: "{{ jellyfin_user.name }}"
    uid: "{{ jellyfin_user.uid }}"
    shell: /sbin/nologin

- name: Add jellyfin user to video group
  ansible.builtin.user:
    name: "{{ jellyfin_user.name }}"
    groups: video
    append: True

# this is specific to ubuntu on a raspberry pi 4
- name: Enable VA-API hardware acceleration
  blockinfile:
    path: /boot/firmware/usercfg.txt
    block: |
      gpu_mem=320
      dtoverlay=vc4-kms-v3d-pi4

- name: Install jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: ghcr.io/linuxserver/jellyfin
    restart_policy: "unless-stopped"
    pull: True
    published_ports:
      - 80:8096 # http web interface
      - 8920:8920 # https web interface
      - 7359:7359/udp # client discovery
      - 1900:1900/udp # DNLA & client discovery
    devices:
      - /dev/vchiq:/dev/vchiq # Raspberry Pi OpenMax video encoding
      - /dev/video10:/dev/video10 # Raspberry Pi V4L2 video encoding
      - /dev/video11:/dev/video11 # Raspberry Pi V4L2 video encoding
      - /dev/video12:/dev/video12 # Raspberry Pi V4L2 video encoding
      - /dev/dri:/dev/dri # Raspberry Pi 4 VA-API hardware acceleration
    volumes: "{{ jellyfin_docker_volumes }}"
    env:
      PUID: "{{ jellyfin_user.uid }}"
      PGID: "{{ jellyfin_user.gid }}"
      TZ: "Europe/Berlin"
