---
- name: Setup gesundheit
  hosts: all
  tags:
    - setup
    - gesundheit
    - monitoring
  become: True
  roles:
    - role: gesundheit
      gesundheit_http_enabled: True
      gesundheit_http_listen_ip: 0.0.0.0
      gesundheit_http_listen_port: 9876
      gesundheit_modules:
        - filename: gotify
          config:
            Handler:
              Module: "gotify"
              Config:
                Url: "{{ vault_gesundheit_gotify_url }}"
                Token: "{{ vault_gesundheit_gotify_token }}"
              Filter:
                - Module: "result-change"
        - filename: check-offsite-backup
          config:
            Check:
              Module: "file-mtime"
              Description: "Check nightly offsite backup"
              Interval: "1h"
              Config:
                Path: "/var/lib/offsite-backup/offsite-backup.stamp"
                MaxAge: "25h"
        - filename: check-jellyfin-health
          config:
            Check:
              Module: "http-status"
              Description: "Check if jellyfin is up & running"
              Interval: "20m"
              Config:
                Method: "GET"
                Url: "http://flix.merse88b.de/health"
                Status: 200
        - filename: check-syncthing-health
          config:
            Check:
              Module: "file-mtime"
              Description: "Check syncthing sync with angerpi"
              Interval: "1h"
              Config:
                Path: "/home/syncthing/health/angerpi.stamp"
                MaxAge: "7h"
        - filename: check-disk-space-root
          config:
            Check:
              Module: "disk-space"
              Description: "Check free space on root partition"
              Interval: "30m"
              Config:
                MountPoint: "/"
                MinAvailable: "1G"
        - filename: check-disk-space-raid-maschine
          config:
            Check:
              Module: "disk-space"
              Description: "Check free space on external RaidMaschine partition"
              Interval: "30m"
              Config:
                MountPoint: "{{ external_drive_paths.RaidMaschine.internal }}"
                MinAvailable: "20G"
        - filename: check-disk-space-fast-maschine
          config:
            Check:
              Module: "disk-space"
              Description: "Check free space on external FastMaschine partition"
              Interval: "30m"
              Config:
                MountPoint: "{{ external_drive_paths.FastMaschine.internal }}"
                MinAvailable: "20G"
        - filename: check-memory
          config:
            Check:
              Module: "memory"
              Description: "Check available memory"
              Interval: "5m"
              Config:
                MinAvailable: "500M"
        - filename: check-reboot-required
          config:
            Check:
              Module: "file-presence"
              Description: "Check if reboot is required"
              Interval: "1h"
              Config:
                Path: "/run/reboot-required"
                Present: False
