---
- hosts: merseflix
  tags:
    - merseflix
    - jellyfin
  roles:
    - role: jellyfin
      jellyfin_docker_volumes:
        - "{{ merseflix_root_path }}/jellyfin:/config"
        - "{{ merseflix_root_path }}/series:/data/series"
        - "{{ merseflix_root_path }}/movies:/data/movies"
      become: True
