---
- hosts: eins
  roles:
  - role: jellyfin
    tags:
      - jellyfin
    jellyfin_docker_volumes:
      - "{{ jellyfin_root_path }}/jellyfin:/config"
      - "{{ jellyfin_root_path }}/series:/data/series"
      - "{{ jellyfin_root_path }}/movies:/data/movies"
