---
- name: Setup netflix, home edition
  hosts: merseflix
  tags:
    - merseflix
  become: True

  pre_tasks:
    - name: Ensure media group exists
      ansible.builtin.group:
        name: "{{ merseflix_name }}"
        state: present
    - name: Add relevant users to media group
      ansible.builtin.user:
        name: "{{ item }}"
        groups:
          - "{{ merseflix_name }}"
        append: True
      with_items: "{{ merseflix_users }}"
      no_log: True

- import_playbook: jellyfin.yml
- import_playbook: samba.yml
- import_playbook: syncthing.yml
