---
- name: Add samba shares
  hosts: merseflix
  tags:
    - merseflix
    - samba
  become: True
  vars:
    samba_system_users:
      - robs

  pre_tasks:
    - name: Create samba system user groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      with_items: "{{ samba_system_users }}"
    - name: Create samba system users
      ansible.builtin.user:
        name: "{{ item }}"
        group: "{{ item }}"
        groups:
          - "{{ merseflix_name }}"
        shell: /sbin/nologin
        password: '!'
        create_home: False
        append: True
      with_items: "{{ samba_system_users }}"

  roles:
    - role: bertvv.samba
      samba_server_string: "merse fileserver %m"
      samba_users: "{{ vault_samba_users }}"
      # the version in ubuntu 20.04 is not affected, see https://github.com/bertvv/ansible-role-samba/pull/61 for details
      samba_mitigate_cve_2017_7494: no
      samba_shares:
        - name: "simon-data"
          comment: "simons data on raid"
          public: no
          group: simon
          valid_users: +simon
          write_list: +simon
          create_mode: "0660"
          force_create_mode: "0660"
          directory_mode: "0770"
          force_directory_mode: "0770"
          path: "{{ external_drive_paths.RaidMaschine.internal }}/data"
        - name: "{{ merseflix_name }}-movies"
          comment: 'dump your movies here!'
          group: "{{ merseflix_name }}"
          write_list: "+{{ merseflix_name }}"
          public: yes
          path: "{{ merseflix_root_path }}/movies"
        - name: "{{ merseflix_name }}-tvshows"
          comment: 'dump your tv shows here!'
          group: "{{ merseflix_name }}"
          write_list: "+{{ merseflix_name }}"
          public: yes
          path: "{{ merseflix_root_path }}/series"
