- hosts: all
  roles:
    - role: common
      tags: ['setup']
    # Get security updates and reboots automaticly
    - role: jnv.unattended-upgrades
      tags: ['setup']
      unattended_automatic_reboot: False
      become: True

- import_playbook: docker.yml
- import_playbook: unifi_controller.yml
- import_playbook: merseflix.yml
