---
dependencies:
  - role: systemli.apt_repositories
    vars:
      apt_repositories:
        - name: ushis.github.io
          url: "https://ushis.github.io/gesundheit/deb/{{ _platform_map[ansible_architecture] | default(ansible_architecture) }}"
          suites: /
          components: ''
          key_path: gesundheit-release-key.gpg
          packages:
            - gesundheit
    become: True
