---
- name: install gesundheit
  ansible.builtin.package:
    name: gesundheit
    state: present
  notify: restart gesundheit service

- name: enable gesundheit service
  ansible.builtin.service:
    name: gesundheit
    enabled: True

- name: configure gesundheit
  ansible.builtin.template:
    src: "gesundheit.toml.j2"
    dest: "/etc/gesundheit/gesundheit.toml"
    owner: root
    group: gesundheit
    mode: "0640"
  notify: restart gesundheit service

- name: configure gesundheit handlers
  ansible.builtin.template:
    src: "module.toml.j2"
    dest: "/etc/gesundheit/modules.d/{{ item.filename }}.toml"
    owner: root
    group: gesundheit
    mode: "0640"
  with_items: "{{ gesundheit_modules }}"
  no_log: True
  notify: restart gesundheit service
