---
- name: copy script to mount external storage
  ansible.builtin.template:
    src: mount-ext-storage.j2
    dest: /usr/local/sbin/mount-ext-storage
    owner: root
    group: root
    mode: '0755'
