---
# configure environment
- name: write stage to /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^STAGE="
    line: "STAGE={{ stage }}"

- name: write stage to /etc/stage
  ansible.builtin.copy:
    content: "{{ stage }}"
    dest: /etc/stage
    mode: "0655"
