---
# write /etc/hosts
- name: write /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"

# write /etc/mailname
- name: write /etc/mailname
  ansible.builtin.template:
    src: mailname.j2
    dest: /etc/mailname
    mode: "0644"

# set hostname
- name: set hostname
  ansible.builtin.hostname:
    name: "{{ register_hosts[0].hostname }}"
