---
# update the repositories
- name: update repositories
  ansible.builtin.apt:
    update_cache: True
    cache_valid_time: 3600
  when: update_repositories is defined and update_repositories == True

# install packages
- name: install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl
      - htop
      - bmon # bandwidth monitoring
      - git-core
      - logrotate
      - ncdu # ncurses disk usage analyzer
      - net-tools
      - python3-dev
      - python3-pip
      - python3-setuptools
      - software-properties-common
      - sudo
      - tree
      - tmux
      - unzip
      - vim-nox
      - zsh
      - zsh-syntax-highlighting

# remove packages
- name: remove packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: absent
    autoremove: True
    purge: True
  vars:
    packages:
    - exim4
    - nfs-common
