---
# add admin groups
- name: add admin groups
  ansible.builtin.group:
    name: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  no_log: True

# add admin users
- name: change root user
  ansible.builtin.user:
    name: root
    shell: /bin/zsh

- name: change ubuntu user
  ansible.builtin.user:
    name: ubuntu
    shell: /bin/zsh

- name: add admin users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    groups:
      - sudo
    shell: /bin/zsh
    password: "{{ item.pass }}"
  with_items: "{{ admin_users }}"
  no_log: True

# omit sudo password (development only)
- name: omit sudo password (development only)
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/development
    create: True
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
  with_items: "{{ admin_users }}"
  no_log: True
  when: stage == "development"

# add grml
- name: add root grml zsh config
  ansible.builtin.get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /root/.zshrc
    owner: root
    group: root

- name: add admin grml zsh config
  ansible.builtin.get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /home/{{ item.name }}/.zshrc
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  no_log: True

# clone zsh autosuggestions
- name: clone zsh autosuggestions repository
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /usr/share/zsh-autosuggestions
    version: "v{{ zsh_autosuggestions_version }}"

# configure zsh
- name: configure root zsh
  ansible.builtin.template:
    src: zshrc.local.j2
    dest: /root/.zshrc.local
    owner: root
    group: root

- name: configure admin zsh
  ansible.builtin.template:
    src: zshrc.local.j2
    dest: "/home/{{ item.name }}/.zshrc.local"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  no_log: True

# add admin ssh keys
- name: add admin ssh keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', 'files/keys/{{ item.name }}.pub') }}"
  with_items: "{{ admin_users }}"
  no_log: True
  when: stage != "development"
