---
- name: Install Matrix Webhook container
  community.docker.docker_container:
    name: "matrix-webhook-{{ matrix_webhook_matrix_id }}"
    image: nim65s/matrix-webhook
    restart_policy: "unless-stopped"
    pull: true
    published_ports:
      - "{{ matrix_webhook_port }}:4785"
    env:
      MATRIX_URL: "{{ matrix_webhook_matrix_url }}"
      MATRIX_ID: "{{ matrix_webhook_matrix_id }}"
      MATRIX_PW: "{{ matrix_webhook_matrix_pw }}"
      API_KEY: "{{ matrix_webhook_api_key }}"
