---
# Create unifi user
- name: Ensure group "{{ unifi_user.name }}" exists
  ansible.builtin.group:
    name: "{{ unifi_user.name }}"
    state: present
    gid: "{{ unifi_user.gid }}"

- name: Create unifi user
  ansible.builtin.user:
    name: "{{ unifi_user.name }}"
    group: "{{ unifi_user.name }}"
    uid: "{{ unifi_user.uid }}"

- name: Install unifi-controller container
  community.docker.docker_container:
    name: unifi-controller
    image: linuxserver/unifi-controller
    restart_policy: "unless-stopped"
    privileged: True
    pull: True
    published_ports:
      - 8080:8080 # required for Unifi to function
      - 3478:3478/udp # Unifi communication port
      - 10001:10001/udp # required for AP discovery
      - 8081:8081 # Unifi communication port
      - 8443:8443 # Unifi communication port, web ui
      - 8843:8843 # Unifi communication port
      - 8880:8880 # Unifi communication port
      - 6789:6789 # For throughput test
      - 5514:5514 # optional
    volumes:
      - "unifi-controller-data:/config"
    env:
      PUID: "{{ unifi_user.uid }}"
      PGID: "{{ unifi_user.gid }}"
