---
- name: install docker
  ansible.builtin.apt:
    name: "docker.io"
    state: present

- name: install docker python bindings
  ansible.builtin.apt:
    name: "python3-docker"
    state: present

- name: Ensure Docker is started & enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
