---
- name: install syncthing
  package:
    name: syncthing
    state: present

- name: Ensure group "{{ syncthing_user }}" exists
  group:
    name: "{{ syncthing_user }}"
    state: present

- name: Create syncthing user
  user:
    name: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
    shell: /sbin/nologin

- name: Add syncthing user to merseflix group
  user:
    name: "{{ syncthing_user }}"
    groups: merseflix
    append: True

- name: Ensure syncthing is started & enabled
  service:
    name: "syncthing@{{ syncthing_user }}"
    state: started
    enabled: True

- import_tasks: health_stamp.yml
